# Generated by Django 5.2.1 on 2025-05-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetosReciclables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMaterial', models.CharField(max_length=30)),
                ('cantidadMaterial', models.IntegerField()),
                ('fechaEstimada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=30)),
                ('direccionUsuario', models.CharField(max_length=40)),
                ('telefonoUsuario', models.CharField(verbose_name=15)),
            ],
        ),
    ]
