# Generated by Django 5.2.1 on 2025-05-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_rename_objetosreciclables_objetosreciclable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
